// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? 'https://zybkhhxvsdjkluqydcbb.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? 'test-anon-key';
const isTestMode = import.meta.env.MODE === 'test';

if (!isTestMode) {
  const missingVars = [
    !import.meta.env.VITE_SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
    !import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
  ].filter(Boolean);

  if (missingVars.length > 0) {
    throw new Error(
      `[supabase] Missing required environment variables: ${missingVars.join(', ')}. ` +
      'Define them in your deployment environment before starting the app.',
    );
  }

  try {
    new URL(SUPABASE_URL);
  } catch {
    throw new Error('[supabase] VITE_SUPABASE_URL must be a valid absolute URL.');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use sessionStorage so the auth token is dropped when the tab / installed
    // PWA is fully closed. This forces re-sign-in on next launch while still
    // surviving page refreshes and in-tab navigations.
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
